### ISSUE TITLE
Update CI

### ISSUE THREAD

**Issue by KennethEnevoldsen** [HLasse/TextDescriptives#79]
- [x] Auto bump version ID, added in #110 
- [x] Auto accept dependabot, added in #110 (or was added beforehand, but at least here)
- [x] Add concurrency to pytests, added in #110 
- [ ] CI for tutorials
- [x] #98
- [x] #99
  - [ ] #108
